# Generated by Django 5.1.7 on 2025-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Checked-in', 'Checked-in'), ('Checked-out', 'Checked-out')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
