# Generated by Django 5.1.7 on 2025-03-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Suite', 'Suite Room'), ('Deluxe', 'Deluxe Room'), ('Family', 'Family Room'), ('Presidential', 'Presidential Suite')], default='Single', max_length=20),
        ),
    ]
